### ISSUE TITLE
[Feature]:DDC support in Virtual Monitor

### ISSUE THREAD

**Issue by mhdAABID** [VirtualDisplay/Virtual-Display-Driver#201]
Hello,

I have installed the IDD sample drivers and i can able to see virtual display on my device's display settings, but it is not supporting for DDC communication.
![IDD details](https://github.com/user-attachments/assets/84a5d722-6366-41b2-b7c4-d9bf15be645c)

Is is possible to have DDC support in virtual display?

please reach me through,
msherif@konrad-technologies.com

**Comment by itsmikethetech** [comment]
What is the use case or specific DDC features you would need? Most of them require a physical monitor, for example, Brightness. We could potentially implement a pass-through, but it would be highly dependent on the actual implementation and hardware.

`// Extend the IddSampleDriver's configuration
IDD_CX_CLIENT_CONFIG driverConfig = {};
IddCxDeviceInitConfig(&driverConfig);

driverConfig.I2cTransaction = MyI2cTransactionHandler; // Implement this
driverConfig.I2cCancelTransaction = MyI2cCancelHandler;

// Handle I2C transactions
NTSTATUS MyI2cTransactionHandler(
    _In_ HANDLE DeviceHandle,
    _In_ ULONG OutputBufferLength,
    _Out_ PVOID OutputBuffer,
    _In_ ULONG InputBufferLength,
    _In_ PVOID InputBuffer)
{
    // Decode the DDC command
    // Forward to physical display or simulate response
    return STATUS_SUCCESS;
}

// Handle DDC commands in user-space accessible functions
`

**Comment by bud3699** [comment]
More of the question, what did you use to get that result in first screenshot

**Comment by nevespt** [comment]
> More of the question, what did you use to get that result in first screenshot

SoftMCCS

**Comment by bud3699** [comment]
Yeh Mike found it for me and sent me it, but what about mikes question?

**Comment by adheshkt** [comment]
@itsmikethetech, 

Yes, you were right; for DDC communication, we need a physical monitor, since the DDC protocol is used to communicate between the host system and monitor, but in my case I have to use this DDC protocol to establish communication between two systems using manufacturer-specific VCP codes. For that I thought to emulate the ghost display in one system and tried to use it as a monitor for the other system, but I am not sure how feasible it is. 

If any of you guys have done it before, please help me out with that.

**Comment by mhdAABID** [comment]
@itsmikethetech

Yes, you were right; for DDC communication, we need a physical monitor, since the DDC protocol is used to communicate between the host system and monitor, but in my case I have to use this DDC protocol to establish communication between two systems using manufacturer-specific VCP codes. For that I thought to emulate the ghost display in one system and tried to use it as a monitor for the other system, but I am not sure how feasible it is.

If any of you guys have done it before, please help me out with that.

**Comment by itsmikethetech** [comment]
Would this need to be in the display driver? I feel like it might be easier to create an application or script that send codes to the remote machine and executes the VCP codes there. Not sure if it would need to be in the driver. While it's theoretically possible to emulate DDC communications in the virtual display, challenges arise because DDC is inherently a hardware-level protocol. Emulation would require creating a software layer anyway that mimics DDC/CI behavior over software interfaces. I think, if I'm understanding the request correctly, the software method would likely be ideal. Difficult to say without knowing specifics though.

You could also stream the ghost display to the second workstation using a remote desktop protocol or something like Sunshine. But this would only show the display, not send or recieve VCP codes. What specific codes or functionality are you attempting to send?

**Comment by bud3699** [comment]
Yeh, without many specific header files containing info on ddc commands you'd have to manually map them, e.g. debug the ddc protocol, send commands, map the hex data from the buffer then emulate it

**Comment by mhdAABID** [comment]
@itsmikethetech , 

Yes, DDC is a hardware-level protocol. My thought is to use DDC communication between two systems.

Let's say, for example, I am running "X" application in system 1, and in system 2, I am using the DDC protocol to get the application status, like application configuration mode. Consider for application configuration mode I have configured VCP code. 
"0xf1" and values 0 represent idle, 1 represents running, and 2 represents error. In this case, whenever I pass the VCP command 0xf1 from system 2 to system 1, system 1 has to reply with the current application status to system 2. This was my actual requirement, and there are no limitations like this would need to be in the display driver.

**Comment by bud3699** [comment]
So you basically just want to use ddc protocol on system 1 from 2 and vice Versa ?

**Comment by mhdAABID** [comment]
@bud3699 ,yes, is it possible?

**Comment by bud3699** [comment]
I should be like i said before, you'd have to map the ddc protocol then emulate it and send it between the devices over rj45 or serial for wired, or totally go wireless. Instead of mapping I may be able to redirect all ddc commands to be sent over protocol in the driver, that way ddc should theoretically be forwarded to a remote display

**Comment by zjoasan** [comment]
This would be a peer2peer protocol over network, i guess? While VDD is a display emulator and we could probably write a DDC forwarder, how would the receiving peer know: 
1. To listen for DDC trafik from the network? 
2. Select which pathway to reply to the sender, since it's not local?
3. Have rules for how to separate DDC from local monitor back or sender?

This seem like a bit outside VDD functionality. But rather a peer2peer based on a proper network protocol.

**Comment by bud3699** [comment]
![null](https://github.com/user-attachments/assets/453e6b4b-8310-4e31-88e8-dad488983adf)

VD = Virtual Display
CL = Client
CL2 = Client2 
RD = real display


It won't matter, DDC commands sent from an app, will return to that, so Client and client 2, can handle the same ddc protocols, VD i can emulate ddc protocol and send the commands through to the client which handles communication between the other client and then the client 2 receives it and sends it. So both systems will think they're connecting to same display over ddc, only problem which may occur is different location buffer. So basically, vd says, hey lets start ddc communicate, client replicates over to client 2 then attempts to send it to the rd however the data describing the location buffer of display won't match

![null (3)](https://github.com/user-attachments/assets/cb70a7c9-c328-4d4c-b932-e451e57a90b3)

**Comment by mhdAABID** [comment]
@bud3699 Thanks for your detailed explanation.

I have one question: What are you mentioning as client 1 and client 2?

**Comment by bud3699** [comment]
That would just be a custom made client made to receive/send data between the devices then use ddc protocol

**Comment by zjoasan** [comment]
client <-> client, for me is a peer2peer. 

So what I'm saying is that you need some way of traverse the network and get the receiver to accept the data, do what it does with it, since this seems to be custom DDC-values and reply . Then send DDC back to a client2 which will send it over the network to original sender, instead of local display. The forwarder isn't the problem, the receiver and reply part might.

**Comment by bud3699** [comment]
No, It doesnt need to do anything with it, like Chinese whispers basically just back and fourth with more accuracy

HEY CLIENT - > HEY CLIENT REPEATED -> HEY CLIENT -> HEY CLIENT
HEY DISPLAY -> HEY DISPLAY REPEATED -> HEY DISPLAY -> HEY DISPLAY

**Comment by bud3699** [comment]
Detected monitors:
1: <Monitor object at 0x000001AD6D02E390>
2: <Monitor object at 0x000001AD6D02E950>
3: <Monitor object at 0x000001AD6D02E290>
4: <Monitor object at 0x000001AD6D36E1D0>


Here is what I'm on about. So ddcutil can return where these monitors objects are stored in memory. Which may be the only problem as when it replicates its attempts to replicate to monitor at an invalid memory address. then we'd need to do pointer memory address mapping, so it would have to be specifically language like c preferably or c++

Hope this clears up confusion

**Comment by mhdAABID** [comment]
@bud3699 Thanks for the explanation; still, I could not be able to follow you. Let me try to understand.

**Comment by bud3699** [comment]
Plus another problem may be calling correct api from the driver due to its limitations, so we'd need to most likely have it send through an ioctl or pipe, but pipe gets cleared so icotl may be best option for this case. ioctl with its own thread, which then communicates with client api

Here's a screenshot
T = Transmit
R = Receive 

![null (3)](https://github.com/user-attachments/assets/67baac4d-b09e-434d-9195-45a84b868431)

If its done this way, that means every ddc app should in theory, just work thinking its a real monitor, whether it will react the same way if two ddc apps are open reading values simultaneously is a different story, that all depends how well their ddc app was made

**Comment by mhdAABID** [comment]
Hello,
Let me explain my requirements first, and then I will share with you the stuff that I have done so far.

**Requirement:** 
To establish communication between two systems using the DDC protocol
![image](https://github.com/user-attachments/assets/982c843c-f8d2-4795-b4c4-cb04fc81b882)

 
Trail 1: 
In trial 1, I used an Arduino to tap I2C signals, but here I am using a monitor, so I cannot play on custom manufacturer-specific VCP codes. So I tried to move to a virtual display since there is flexibility to play with custom VCP codes.
![image](https://github.com/user-attachments/assets/bc803ddf-2e7a-4799-b801-8bb75b45d51b)
`

**Comment by mhdAABID** [comment]
I hope this will align as to stick with the requirement

**Comment by bud3699** [comment]
Ah, i see, that will be a problem if its manufacturer specific for monitor you wont be able to get the manufacturer specific vcp codes, thats handled completely in the monitor, so even if the driver were to emulate it, it won't show anything. it would be physically impossible without a real display, we can emulate a real display but the real display must be connected so we can interact with that instead, otherwise use real display, map all vcp commands then emulate each command response, so for example

if received 0x09 then force it to respond with 0x07 (These arent real values just for example purposes). But we'd need to already know the specific data

**Comment by mhdAABID** [comment]
These VCP codes are programmed in the monitor's firmware, right? Are there any possible ways to reach that, and are there any other ways to map or reprogram the monitor's MCCs?

**Comment by bud3699** [comment]
Yeh, the VCP codes will be in monitors firmware, only way i can think is you may be able to attach an awd programmer to the rom chip and dump the firmware then you'll need to find a way to dump the mccs section then decrypt vcp codes, the same method could be used for re-writing the monitors mccs but again you'd need to figure out how the rom chip actually stores its data, one way which could work is if you had the monitor then it had some kind of bootloader for updating it, that way you can push custom assembly code to the bootloader and get it to dump over to a usb or something, but you'd still need the real monitor itself

**Comment by bud3699** [comment]
to be more specific for assembly, i guess, load flash into memory then somehow reply it to the usb, we'd need a storage handler most likely, shame monitors don't have dedicated uart ports

**Comment by mhdAABID** [comment]
Do you have any previous experience with booting a monitor's firmware? If yes, can you please explain it to me?

**Comment by bud3699** [comment]
its not something you can just boot, even if you had the firmware you'd need to emulate it, if the firmware is made for specific hardware requirements then you'd have to emulate everything. So that's not really an option. So right now, its looking like the only way you can find specific vcp codes is if you had the actual monitor and like you did in trial screenshots

**Comment by bud3699** [comment]
On another note, why do you need the systems to communicate with ddc with manufacturer specific codes?

**Comment by mhdAABID** [comment]
Yes, there are many other ways, but still I am passing video data from system 1 to system 2. I just want to do the communication in the same line.

**Comment by bud3699** [comment]
how are you handling the video data from system 1 to system 2 ?

**Comment by mhdAABID** [comment]
The bad thing is the capture card that I am using in system 2 does not support DDC. That's where the issue arises.

**Comment by bud3699** [comment]
ohhhhh, so System 2 has capture card, and system 1 screen goes to system 2 but you want to control system 1 screen from system 2???

**Comment by mhdAABID** [comment]
Yes, more or less like that.

**Comment by bud3699** [comment]
Well you cant send vcp data over the hdmi if the i2c/ddc protocols aren't in place on that capture card. And you probably won't get any capture card which has that since its not a real display

**Comment by mhdAABID** [comment]
Yes, that's where I got blocked. But still I have to do it with DDC.

**Comment by bud3699** [comment]
No problemo, i'll close it as not planned but if you need to reach me, you can reach me for whatever reason, you can reach me through my discord or email

discord: bud3699
email: bud3699@gmail.com
